# Generated by Django 5.2.4 on 2025-09-13 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itineraries', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itineraryday',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='itineraryitem',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='itineraries.itineraryday'),
        ),
        migrations.AlterUniqueTogether(
            name='itineraryday',
            unique_together={('trip', 'date')},
        ),
    ]
