# Generated by Django 5.2.4 on 2025-11-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itineraryitem',
            name='estimated_time',
            field=models.CharField(blank=True, help_text="e.g., '2-3 hours', 'Half Day'", max_length=50, null=True),
        ),
    ]
