# Generated by Django 5.2.4 on 2025-07-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_trip_location_trip_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='name',
            new_name='title',
        ),
    ]
