# Generated by Django migrations for backend app

from django.db import migrations


class Migration(migrations.Migration):
    """
    Initial migration for the backend app.
    
    This migration is intentionally empty because the backend app only contains
    BaseModel, which is an abstract model (defined in backend/backend/models.py).
    Abstract models do not create database tables, so no operations are needed.
    
    This migration exists to satisfy Django's migration system requirements and
    prevent errors when running manage.py migrate or makemigrations commands.
    """

    initial = True

    dependencies = [
    ]

    operations = [
    ]
