# Generated by Django 5.2.4 on 2025-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='duration',
            field=models.PositiveIntegerField(default=1, help_text='Duration in days'),
        ),
        migrations.AddField(
            model_name='trip',
            name='member_spots',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
