# Generated by Django 5.2.4 on 2025-10-02 16:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_system', models.BooleanField(default=False)),
                ('usage_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('CHALLENGING', 'Challenging')], default='EASY', max_length=15),
        ),
        migrations.AddField(
            model_name='tripmember',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'Organizer'), ('CO_ORGANIZER', 'Co-Organizer'), ('MEMBER', 'Member')], default='MEMBER', max_length=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='trips', to='trips.tag'),
        ),
    ]
