# Generated by Django 5.2.4 on 2025-10-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tag_trip_difficulty_tripmember_role_trip_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='location',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
