# Generated by Django 5.2.4 on 2025-10-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_trip_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripmember',
            name='dietary_restrictions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tripmember',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tripmember',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
