# Generated by Django 5.2.4 on 2025-11-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_tripmember_dietary_restrictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_joinable',
            field=models.BooleanField(default=True),
        ),
    ]
