# Generated by Django 5.2.4 on 2025-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_trip_is_joinable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='trip',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
