# Generated by Django 5.2.4 on 2025-12-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_alter_trip_description_alter_trip_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripmember',
            options={'ordering': ['-joined_at']},
        ),
    ]
