# Generated by Django 5.2.4 on 2025-10-16 15:08

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.db.models.functions.datetime.Now),
        ),
    ]
