# Generated by Django 5.2.4 on 2025-10-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
