# Generated by Django 5.2.4 on 2025-10-05 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_alter_packingcategory_name'),
        ('trips', '0006_tag_trip_difficulty_tripmember_role_trip_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingitem',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trips.tripmember'),
        ),
        migrations.AlterField(
            model_name='packingitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='packing.packingcategory'),
        ),
    ]
