# Generated by Django 5.2.4 on 2025-10-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0004_alter_packingitem_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packingitem',
            options={'ordering': ['-created_at']},
        ),
    ]
