# Generated by Django 5.2.4 on 2025-10-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='category',
            field=models.CharField(choices=[('PRE_TRIP', 'Pre-Trip'), ('DURING_TRIP', 'During Trip'), ('POST_TRIP', 'Post-Trip')], default='PRE_TRIP', max_length=20),
        ),
        migrations.DeleteModel(
            name='ChecklistCategory',
        ),
    ]
