# Generated by Django 5.2.4 on 2025-11-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_alter_checklistitem_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['-created_at']},
        ),
    ]
