# Generated by Django 5.2.4 on 2025-11-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_checklistitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
