# Generated by Django 5.2.4 on 2025-12-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0004_alter_checklistitem_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'ordering': ['-due_date', 'position']},
        ),
    ]
